Feat/views and partials
shadabwahidullah/Blog-App pull request #6
Opened 2022-09-21 16:56 UTC by shadabwahidullah

## Changes included in this milestone
### Added partials
- User partial
- Post partial
- Comments partial
### Modified
- User
  - Index
  - Show
- Post
  - Index
  - Show

2022-09-21 18:07 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @shadabwahidullah,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Gitflow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] There is a problem happening when you try to add new users or posts to the database nothing gets saved and that's happening because the validations you add to user and post models for `posts_counter`, `comments_counter`, and `likes_counter`. 
There are two solutions: 
The first one: is to add a default value of zero for these variables in the migration files for creating users and posts tables.
The second one: is to add `allow_blank: true` rule at the end of the validation lines for `likes_counter`, `comments_counter`, and `posts_counter` in both user and post models.

https://github.com/shadabwahidullah/Blog-App/blob/0f5b82c134ddcec414f870e562f54a77062482f8/app/models/user.rb#L7

https://github.com/shadabwahidullah/Blog-App/blob/0f5b82c134ddcec414f870e562f54a77062482f8/app/models/post.rb#L7-L8

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-21 18:07 UTC, omar-muhamad commented on app/views/shared/_user.html.erb
> +      </div>
- [x] This div suppose to be a link when you click on it it takes you to the user show page for this specific user. So please fix this.
[Hint] See this [article ](https://www.rubyguides.com/2019/05/rails-link_to-method/)it will help.

2022-09-21 18:07 UTC, omar-muhamad commented on app/views/shared/_post.html.erb
> +    </div>
- [x] Same here, This div suppose to be a link when you click on it it takes you to the post show page for this specific post. So please fix this.
[Hint] See this [article ](https://www.rubyguides.com/2019/05/rails-link_to-method/)it will help.

2022-09-21 18:07 UTC, omar-muhamad commented on app/views/users/show.html.erb
> +   </div>
- [x] Please add the `see all posts` button here at the end of the user show page to match the given design.

![image](https://user-images.githubusercontent.com/68796232/191576146-bf1fee0c-5621-41bb-8515-9f8d703ded30.png)

2022-09-23 20:08 UTC, shadabwahidullah commented on app/views/shared/_user.html.erb
> +      </div>
thanks, done

2022-09-23 20:08 UTC, shadabwahidullah commented on app/views/shared/_post.html.erb
> +    </div>
thanks, done

2022-09-23 20:09 UTC, shadabwahidullah commented on app/views/users/show.html.erb
> +   </div>
Thanks for pointing this out. done

2022-09-23 20:19 UTC, t-yanick approved these changes
Hi @shadabwahidullah , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 20:23 UTC, merged